### ISSUE TITLE
How to statistics scalar like temperature with this tool?

### ISSUE THREAD

**Issue by zhoulei3A** [adampep/KTH_Toolbox#11]
How to statistics scalar like temperature with this tool?
For example, temperature variance, temperature heat flux, temperature budget……? Could you give me some guidance? I couldn't find it in the examples.

**Comment by adampep** [comment]
There is a version of statistics tool including temperature. Please contact timofeymukha

**Comment by zhoulei3A** [comment]
Thanks for info, Adam.

Hi, Timofey, @timofeymukha Could you give me some help about how to statistics temperature with this toolbox? Thanks very much.

Best regards,
Lei

**Comment by timofeymukha** [comment]
Hi @zhoulei3A , sorry I wasn't paying attention to GH notifications for a long while. Have you managed to solve this?

You can look at the statistics code in this repo
https://github.com/timofeymukha/nekwmles/blob/master/examples/channel_flow/compile/stat.f

It contains temperature, but also a bunch of WMLES stuff that you probably don't need. You can modify accordingly.
